name: Build Tweak
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Randomblock1/theos-action@v1
      - name: Build Tweak
        run: make package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyTweak-Package
          path: packages/*.deb
